//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KidsAcademy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class countingTable
    {
        public int counting_id { get; set; }
        public string counting_image { get; set; }
        public string counting_imageLarge { get; set; }
    }
}
