//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adminpanel.Models
{
    using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web;
    
    public partial class countingTable
    {
        public int counting_id { get; set; }
        [DisplayName("Upload Small Image")]
        public string counting_image { get; set; }
        [DisplayName("Upload Large Image")]
        public string counting_imageLarge { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
        public HttpPostedFileBase ImageFileOne { get; set; }
    }
}
