//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adminpanel.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web;
    
    public partial class poemTable
    {
        public int poem_id { get; set; }
        public string poem_name { get; set; }
        [DisplayName("Upload Image")]
        public string poem_image { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
    }
}
